import json
import os
from pathlib import Path
import subprocess
from tempfile import TemporaryDirectory
from types import SimpleNamespace
from unittest.mock import patch

import numpy as np
import pytest

from MoosasPy.simulation.airflow.network import (
    NETWORK_SCHEMA_VERSION,
    AfnPath,
    AfnZone,
    _build_leakage_path_from_space,
    _load_network_payload,
    buildNetworkFile,
    buildZoneInfoFile,
)
from MoosasPy.model import MoosasModel
from MoosasPy.simulation.airflow import AirflowRunner
from MoosasPy.simulation.airflow.runner import VentPaths
from MoosasPy.simulation.radiation import calculate_model_radiation
from MoosasPy.simulation.weather.sky.cumulative import CumulativeSky


def _zone():
    return AfnZone(
        userName="room",
        temperature=27.0,
        prjIndex=1,
        prjName="z001",
        heatLoad=100.0,
        volume=30.0,
        position_x=2.0,
        position_y=1.5,
        position_z=1.5,
        boundary="0 0 4 0 4 3 0 3",
        level=0.0,
        levelIndex=1,
        relHt=1.5,
        contam={},
    )


def _opening():
    return AfnPath(
        userName="window",
        prjIndex=1,
        pathHeight=2.0,
        pathWidth=1.0,
        position_x=0.0,
        position_y=1.5,
        position_z=1.5,
        fromZone=-1,
        toZone=1,
        pressure=0.0,
        winType=1,
        orientation=[1.0, 0.0, 0.0],
        pathType="glazing",
        level=0.0,
        levelIndex=1,
        relHt=1.5,
        contam={},
        operable=0.5,
    )


def test_network_file_uses_json_schema_and_preserves_operable_scaling_marker():
    with TemporaryDirectory() as directory:
        output = Path(directory) / "network.json"
        buildNetworkFile(pathList=[_opening()], zoneList=[_zone()], networkFilePath=str(output))
        payload = json.loads(output.read_text(encoding="utf-8"))

    assert payload["schemaVersion"] == NETWORK_SCHEMA_VERSION
    assert payload["levels"] == [{"nr": 1, "refht": 0.0, "delht": 3.0, "name": "<1>"}]
    assert payload["zones"]["room"]["prjName"] == "z001"
    assert payload["paths"]["window"]["element"]["dtype"] == "dor_pl2"
    assert payload["paths"]["window"]["element"]["operable"] == 0.5
    assert payload["paths"]["window"]["element"]["_autoGenerated"] is True


def test_zone_info_reads_json_network_directly():
    payload = {
        "schemaVersion": NETWORK_SCHEMA_VERSION,
        "levels": [{"nr": 1, "refht": 0.0, "delht": 3.0, "name": "<1>"}],
        "zones": {"room": _zone().toDict()},
        "paths": {"window": _opening().toDict()},
    }
    text = buildZoneInfoFile(networkDict=payload)

    assert "z001,100.0,room" in text


def test_legacy_net_input_is_rejected():
    with TemporaryDirectory() as directory:
        input_path = Path(directory) / "network.net"
        input_path.write_text("room,z001,100,27,30,2,1.5,1.5,0 0 4 0", encoding="utf-8")
        with pytest.raises(json.JSONDecodeError):
            _load_network_payload(str(input_path))


def test_leakage_path_connects_zone_to_ambient():
    space = SimpleNamespace(level=0.0, getWeightCenter=lambda: [2.0, 1.5, 1.5])
    zone = _zone()
    with patch(
        "MoosasPy.simulation.airflow.network._space_height_for_leakage", return_value=3.0
    ), patch(
        "MoosasPy.simulation.airflow.network._space_exterior_facade_width", return_value=12.0
    ):
        leakage = _build_leakage_path_from_space(space, zone)

    assert leakage.pathType == "leakage"
    assert leakage.fromZone == -1
    assert leakage.toZone == 1
    assert leakage.pathHeight == 3.0
    assert leakage.pathWidth == 12.0
    assert leakage.element["dtype"] == "plr_leak3"
    assert leakage.element["area3"] == 1e-5


def test_moosas_afn_binary_generates_prj_from_json():
    executable_name = "MoosasAFN.exe" if os.name == "nt" else "MoosasAFN"
    executable = Path(__file__).parents[1] / "MoosasPy" / "libs" / "vent" / executable_name
    payload = {
        "schemaVersion": NETWORK_SCHEMA_VERSION,
        "levels": [{"nr": 1, "refht": 0.0, "delht": 3.0, "name": "<1>"}],
        "zones": {"room": _zone().toDict()},
        "paths": {"window": _opening().toDict()},
    }

    with TemporaryDirectory() as directory:
        work_dir = Path(directory)
        network_file = work_dir / "network.json"
        network_file.write_text(json.dumps(payload), encoding="utf-8")
        result = subprocess.run(
            [str(executable), "-p", "smoke", "-d", str(work_dir), "-s", "0", str(network_file)],
            capture_output=True,
            text=True,
            check=True,
        )
        project_text = (work_dir / "smoke.prj").read_text(encoding="utf-8")

    assert "create such prjFile" in result.stdout
    assert "30.00 300.15 0.00 z001" in project_text
    assert "0.222222 1.000000 0.500000 0.780000" in project_text


def test_rdf_model_runs_airflow_simulation():
    rdf_path = Path(__file__).parent / "caseFile" / "NBuilding.rdf"
    model = MoosasModel.load(rdf_path)
    zero_sky = CumulativeSky(np.zeros(145))
    calculate_model_radiation(
        model,
        {"summer": zero_sky, "winter": zero_sky},
        reflection=0,
    )

    with TemporaryDirectory() as directory:
        result = AirflowRunner(
            model=model,
            paths=VentPaths.create(work_dir=directory),
            max_iterations=2,
            timeout_seconds=60,
        ).run()

    assert len(result.zones) == len(model.spaceList)
    assert result.airflow_matrix.shape == (len(model.spaceList) + 1,) * 2
    assert result.iteration_count == 2
    assert len(result.commands) == 5
    assert all(command.returncode == 0 for command in result.commands)
    assert all(len(zone.temperatures) == 2 for zone in result.zones)
    assert all(len(zone.ach_values) == 2 for zone in result.zones)
