"""
    Corresponding with MoosasAFN.exe
    More information can be found by sending MoosasAFN.exe -h in command line
"""
from __future__ import annotations

import json
import os

from ..geometry.element import *
from ..geometry.geos import Vector
from ..rad import modelRadiation
from ..utils.constant import geom
from ..utils.tools import path, generate_code, callCmd, parseFile
from ..weather.cumsky import MoosasCumSky


VENT_EXE_SUFFIX = ".exe" if os.name == "nt" else ""
NETWORK_SCHEMA_VERSION = 1


def _safe_float(value, default=0.0):
    if value is None:
        return default
    if isinstance(value, str) and value.strip().lower() in ("", "none", "null", "nan"):
        return default
    try:
        return float(value)
    except Exception:
        return default


def _safe_int(value, default=0):
    if value is None:
        return default
    if isinstance(value, str) and value.strip().lower() in ("", "none", "null", "nan"):
        return default
    try:
        return int(float(value))
    except Exception:
        return default


def _normalize_contam_overrides(raw_value):
    if isinstance(raw_value, dict):
        return dict(raw_value)
    return {}


def _coerce_operable(value, default=1.0):
    if value is None:
        return default
    if isinstance(value, bool):
        return 1.0 if value else 0.0
    if isinstance(value, str):
        text = value.strip().lower()
        if text in {"", "none", "null"}:
            return default
        if text in {"true", "yes", "y", "open"}:
            return 1.0
        if text in {"false", "no", "n", "closed"}:
            return 0.0
    try:
        return float(value)
    except Exception:
        return default


def _vector_to_data(value):
    if value is None:
        return None
    try:
        return [float(i) for i in list(value)]
    except Exception:
        return value


def _build_level_objects(level_values: list[float] | None) -> list[dict]:
    levels = sorted({_safe_float(level, 0.0) for level in (level_values or [0.0])})
    if not levels:
        levels = [0.0]
    result = []
    for i, refht in enumerate(levels):
        if i < len(levels) - 1:
            delht = levels[i + 1] - refht
        elif len(levels) > 1:
            delht = levels[-1] - levels[-2]
        else:
            delht = 3.0
        if abs(delht) < geom.POINT_PRECISION:
            delht = 3.0
        result.append({
            "nr": i + 1,
            "refht": float(refht),
            "delht": float(delht),
            "name": f"<{i + 1}>",
        })
    return result


def _infer_levels_from_zones(zoneList) -> list[dict]:
    level_values = []
    for zone in zoneList or []:
        level_values.append(_safe_float(getattr(zone, "level", 0.0), 0.0))
    return _build_level_objects(level_values)


def _normalize_level_name(level_name, level_index):
    text = str(level_name).strip() if level_name is not None else ""
    return text if text else f"<{level_index}>"


def _default_path_element_dict(path_like=None, win_type=1, prj_index=0, user_name="", path_height=0.0, path_width=0.0,
                               operable=1.0, path_type=None, dtype=None):
    h = max(_safe_float(path_height, 0.0), 0.0)
    w = max(_safe_float(path_width, 0.0), 0.0)
    op = max(_coerce_operable(operable, 1.0), 0.0)
    denom = h + w
    lam = h * w * h * w / denom * 0.02028 if denom > geom.POINT_PRECISION else 0.0
    turb = h * w * 0.551543
    element_name = f"p{max(_safe_int(prj_index, 0), 0)}"
    dtype = str(dtype or "").strip()
    if not dtype:
        dtype = "plr_leak3" if str(path_type).strip().lower() == "leakage" else ("dor_pl2" if _safe_int(win_type, 1) == 1 else "plr_conn")
    result = {
        "icon": 27,
        "dtype": dtype,
        "name": element_name if element_name != "p0" else str(user_name or ""),
        "desc": "",
        "operable": op,
        "_autoGenerated": True,
        "lam": lam,
        "turb": turb,
        "expt": 0.65 if dtype == "plr_leak3" else 0.5,
    }
    if result["dtype"] == "dor_pl2":
        result.update({
            "dH": h * 0.222222,
            "ht": h,
            "wd": w,
            "cd": 0.78,
            "u_H": 0,
            "u_W": 0,
        })
    elif result["dtype"] == "plr_leak3":
        result.update({
            "coef": 1.0,
            "pres": 4.0,
            "area1": 0.0,
            "area2": 0.0,
            "area3": 1e-5,
            "u_A1": 0,
            "u_A2": 0,
            "u_A3": 0,
            "u_dP": 0,
        })
    else:
        result.update({
            "area": h * w,
            "coef": 0.65,
            "u_A": 0,
        })
    return result


def _normalize_path_element_data(raw_value, *, path_height=0.0, path_width=0.0, win_type=1, prj_index=0, user_name="",
                                 operable=None, path_type=None):
    if isinstance(raw_value, dict):
        element = dict(raw_value)
    else:
        element = {}
    legacy_operable = operable if operable is not None else element.get("operable", 1.0)
    defaults = _default_path_element_dict(
        win_type=win_type,
        prj_index=prj_index,
        user_name=user_name,
        path_height=path_height,
        path_width=path_width,
        operable=legacy_operable,
        path_type=path_type,
    )
    dtype = str(element.get("dtype") or defaults.get("dtype") or "").strip()
    auto_generated = bool(element.get("_autoGenerated", False)) or not bool(raw_value)
    element["icon"] = _safe_int(element.get("icon"), _safe_int(defaults.get("icon"), 27))
    element["dtype"] = dtype
    element["name"] = str(element.get("name") or defaults.get("name") or "")
    element["desc"] = str(element.get("desc") or "")
    element["operable"] = _coerce_operable(element.get("operable", legacy_operable), defaults.get("operable", 1.0))
    if not dtype:
        element["dtype"] = defaults["dtype"]
    for key, value in defaults.items():
        if auto_generated and key not in {"desc"}:
            element[key] = value
        elif key not in element or element[key] is None or (isinstance(element[key], str) and element[key].strip() == ""):
            element[key] = value
    if "fpc" in element and isinstance(element["fpc"], tuple):
        element["fpc"] = list(element["fpc"])
    if "points" in element and isinstance(element["points"], tuple):
        element["points"] = list(element["points"])
    if "subElements" in element and isinstance(element["subElements"], tuple):
        element["subElements"] = list(element["subElements"])
    return element


def _space_height_for_leakage(space) -> float:
    try:
        return max(_safe_float(getattr(space, "height", 0.0), 0.0), 0.0)
    except Exception:
        return 0.0


def _space_exterior_facade_width(space) -> float:
    width = 0.0
    try:
        faces = space.getAllFaces(to_dict=False)
    except Exception:
        return 0.0
    outer_walls = []
    for face in faces:
        if isinstance(face, MoosasWall) and getattr(face, "isOuter", False):
            outer_walls.append(face)
    for wall in outer_walls:
        try:
            width += float(shapely.length(wall.force_2d()))
        except Exception:
            try:
                width += float(wall.length)
            except Exception:
                continue
    return max(width, 0.0)


def _space_has_exterior_opening(space) -> bool:
    try:
        faces = space.getAllFaces(to_dict=False)
    except Exception:
        return False
    for face in faces:
        if isinstance(face, MoosasWall) and getattr(face, "isOuter", False) and getattr(face, "glazingElement", None):
            return True
        if isinstance(face, MoosasSkylight) and getattr(face, "isOuter", True):
            return True
    return False


def _build_leakage_path_from_space(space, zone: "AfnZone") -> "AfnPath | None":
    height = _space_height_for_leakage(space)
    width = _space_exterior_facade_width(space)
    if height <= geom.POINT_PRECISION or width <= geom.POINT_PRECISION:
        return None
    center = None
    try:
        center = space.getWeightCenter()
    except Exception:
        center = Vector([0.0, 0.0, getattr(zone, "level", 0.0) + height * 0.5])
    pos_x = float(center[0]) if center is not None else 0.0
    pos_y = float(center[1]) if center is not None else 0.0
    level = _safe_float(getattr(zone, "level", getattr(space, "level", 0.0)), 0.0)
    return AfnPath(
        userName=f"{zone.userName}_leakage",
        prjIndex=0,
        pathHeight=height,
        pathWidth=width,
        position_x=pos_x,
        position_y=pos_y,
        position_z=level + height * 0.5,
        fromZone=-1,
        toZone=int(zone.prjIndex),
        pressure=0.0,
        winType=0,
        orientation=Vector([0, 0, 1]),
        level=level,
        levelIndex=int(getattr(zone, "levelIndex", 1)),
        relHt=height * 0.5,
        contam={},
        pathType="leakage",
        element={
            "dtype": "plr_leak3",
            "_autoGenerated": True,
            "expt": 0.65,
            "coef": 1.0,
            "pres": 4.0,
        },
        geometry=None,
    )


def _normalize_zone_dict(zone_data: dict, fallback_key=None, fallback_index=0) -> dict:
    zone = dict(zone_data or {})
    zone["userName"] = str(zone.get("userName") or fallback_key or "")
    zone["prjIndex"] = _safe_int(zone.get("prjIndex"), fallback_index)
    zone["prjName"] = str(zone.get("prjName") or ('z' + '%03d' % max(zone["prjIndex"], 0)))
    zone["temperature"] = _safe_float(zone.get("temperature"), 27.0)
    zone["heatLoad"] = _safe_float(zone.get("heatLoad"), 0.0)
    zone["volume"] = _safe_float(zone.get("volume"), 0.0)
    zone["position_x"] = _safe_float(zone.get("position_x"), 0.0)
    zone["position_y"] = _safe_float(zone.get("position_y"), 0.0)
    zone["position_z"] = _safe_float(zone.get("position_z"), 0.0)
    zone["boundary"] = str(zone.get("boundary") or "")
    zone["level"] = _safe_float(zone.get("level"), 0.0)
    zone["levelIndex"] = _safe_int(zone.get("levelIndex"), 1)
    zone["relHt"] = _safe_float(zone.get("relHt"), 0.0)
    zone["contam"] = _normalize_contam_overrides(zone.get("contam"))
    return zone


def _normalize_path_dict(path_data: dict, fallback_key=None, fallback_index=0) -> dict:
    path_item = dict(path_data or {})
    path_item["userName"] = str(path_item.get("userName") or fallback_key or "")
    path_item["prjIndex"] = _safe_int(path_item.get("prjIndex"), fallback_index)
    path_item["pathType"] = str(path_item.get("pathType") or path_item.get("type") or "").strip() or (
        "leakage" if str((path_item.get("element") or {}).get("dtype", "")).strip().lower() == "plr_leak3" else "opening"
    )
    path_item["pathHeight"] = _safe_float(path_item.get("pathHeight"), 0.0)
    path_item["pathWidth"] = _safe_float(path_item.get("pathWidth"), 0.0)
    path_item["position_x"] = _safe_float(path_item.get("position_x"), 0.0)
    path_item["position_y"] = _safe_float(path_item.get("position_y"), 0.0)
    path_item["position_z"] = _safe_float(path_item.get("position_z"), 0.0)
    path_item["fromZone"] = _safe_int(path_item.get("fromZone"), -1)
    path_item["toZone"] = _safe_int(path_item.get("toZone"), -1)
    path_item["pressure"] = _safe_float(path_item.get("pressure"), 0.0)
    path_item["winType"] = _safe_int(path_item.get("winType"), 1)
    path_item["orientation"] = _safe_float(path_item.get("orientation"), 0.0)
    path_item["level"] = _safe_float(path_item.get("level"), 0.0)
    path_item["levelIndex"] = _safe_int(path_item.get("levelIndex"), 1)
    path_item["relHt"] = _safe_float(path_item.get("relHt"), 0.0)
    path_item["contam"] = _normalize_contam_overrides(path_item.get("contam"))
    path_item["element"] = _normalize_path_element_data(
        path_item.get("element"),
        path_height=path_item["pathHeight"],
        path_width=path_item["pathWidth"],
        win_type=path_item["winType"],
        prj_index=path_item["prjIndex"],
        user_name=path_item["userName"],
        operable=path_item.get("operable"),
        path_type=path_item["pathType"],
    )
    path_item.pop("operable", None)
    return path_item


def _normalize_network_payload_data(payload: dict | None, levels_hint=None) -> dict:
    payload = dict(payload or {})
    payload["schemaVersion"] = _safe_int(payload.get("schemaVersion"), NETWORK_SCHEMA_VERSION)

    raw_levels = payload.get("levels")
    if raw_levels and isinstance(raw_levels, list) and isinstance(raw_levels[0], dict):
        level_objects = []
        for i, level in enumerate(raw_levels, start=1):
            nr = _safe_int(level.get("nr"), i)
            level_objects.append({
                "nr": nr,
                "refht": _safe_float(level.get("refht"), 0.0),
                "delht": _safe_float(level.get("delht"), 3.0),
                "name": _normalize_level_name(level.get("name"), nr),
            })
    else:
        level_objects = _build_level_objects(raw_levels if isinstance(raw_levels, list) else levels_hint)
    payload["levels"] = level_objects

    raw_zones = payload.get("zones", {})
    zone_map = {}
    if isinstance(raw_zones, dict):
        for i, (key, zone) in enumerate(raw_zones.items(), start=1):
            normalized = _normalize_zone_dict(zone, fallback_key=key, fallback_index=i)
            zone_map[normalized["userName"] or str(key)] = normalized
    elif isinstance(raw_zones, list):
        for i, zone in enumerate(raw_zones, start=1):
            normalized = _normalize_zone_dict(zone, fallback_index=i)
            zone_map[normalized["userName"] or f"zone_{i}"] = normalized
    payload["zones"] = zone_map

    raw_paths = payload.get("paths", {})
    path_map = {}
    if isinstance(raw_paths, dict):
        for i, (key, path_item) in enumerate(raw_paths.items(), start=1):
            normalized = _normalize_path_dict(path_item, fallback_key=key, fallback_index=i)
            path_map[normalized["userName"] or str(key)] = normalized
    elif isinstance(raw_paths, list):
        for i, path_item in enumerate(raw_paths, start=1):
            normalized = _normalize_path_dict(path_item, fallback_index=i)
            path_map[normalized["userName"] or f"path_{i}"] = normalized
    payload["paths"] = path_map
    return payload


def _load_network_payload(networkFilePath: str) -> dict:
    with open(networkFilePath, "r", encoding="utf-8", errors="ignore") as f:
        content = f.read()
    stripped = content.lstrip()
    if stripped.startswith("{"):
        return _normalize_network_payload_data(json.loads(content))

    zone_rows = []
    path_rows = []
    for arr in parseFile(networkFilePath)[0]:
        if len(arr) == 9:
            zone_rows.append(arr)
        elif len(arr) >= 10:
            path_rows.append(arr)

    payload = {
        "schemaVersion": 0,
        "levels": _build_level_objects([0.0]),
        "zones": {},
        "paths": {},
    }
    for arr in zone_rows:
        zone_data = {
            "userName": arr[0],
            "prjIndex": _safe_int(arr[1].lower().replace("z", ""), len(payload["zones"]) + 1),
            "prjName": arr[1],
            "heatLoad": _safe_float(arr[2]),
            "temperature": _safe_float(arr[3]),
            "volume": _safe_float(arr[4]),
            "position_x": _safe_float(arr[5]),
            "position_y": _safe_float(arr[6]),
            "position_z": _safe_float(arr[7]),
            "boundary": arr[8],
            "level": 0.0,
            "levelIndex": 1,
            "relHt": 0.0,
            "contam": {},
        }
        payload["zones"][zone_data["userName"]] = zone_data
    for arr in path_rows:
        path_data = {
            "userName": arr[0],
            "prjIndex": _safe_int(arr[1].lower().replace("p", ""), len(payload["paths"]) + 1),
            "pathHeight": _safe_float(arr[2]),
            "pathWidth": _safe_float(arr[3]),
            "position_x": _safe_float(arr[4]),
            "position_y": _safe_float(arr[5]),
            "position_z": _safe_float(arr[6]),
            "fromZone": -1 if _safe_int(arr[7], -1) == -1 else _safe_int(arr[7], -1) + 1,
            "toZone": -1 if _safe_int(arr[8], -1) == -1 else _safe_int(arr[8], -1) + 1,
            "pressure": _safe_float(arr[9]),
            "winType": _safe_int(arr[10], 1) if len(arr) >= 11 else 1,
            "level": 0.0,
            "levelIndex": 1,
            "relHt": 0.0,
            "contam": {},
        }
        payload["paths"][path_data["userName"]] = path_data
    return _normalize_network_payload_data(payload)


class AfnZone(object):
    """
        input for networkFile(zones):
        zoneName: user define zoneName
        heatLoad: total heat load in Watt (W)
        temperature: zone initial temperature (C)
        volume: zone volume (m3)
        positionX,positionY,positionZ: a position to match the zone in meter (m)
        boundaryPolygon: define the zone boundary in meter (m) with ' ' as sep
    """
    __slots__ = ['userName', 'temperature', 'prjIndex', 'prjName', 'heatLoad', 'volume', 'position_x', 'position_y',
                 'position_z', 'boundary', 'level', 'levelIndex', 'relHt', 'contam', 'element']

    def __init__(self, **kwargs):
        for key in self.__slots__:
            if key in kwargs.keys():
                setattr(self, key, kwargs[key])
        self.prjIndex = _safe_int(getattr(self, 'prjIndex', 0), 0)
        self.prjName = str(getattr(self, 'prjName', "") or "")
        self.temperature = _safe_float(getattr(self, 'temperature', 27.0), 27.0)
        self.heatLoad = _safe_float(getattr(self, 'heatLoad', 0.0), 0.0)
        self.volume = _safe_float(getattr(self, 'volume', 0.0), 0.0)
        self.position_x = _safe_float(getattr(self, 'position_x', 0.0), 0.0)
        self.position_y = _safe_float(getattr(self, 'position_y', 0.0), 0.0)
        self.position_z = _safe_float(getattr(self, 'position_z', 0.0), 0.0)
        self.boundary = str(getattr(self, 'boundary', "") or "")
        self.level = _safe_float(getattr(self, 'level', 0.0), 0.0)
        self.levelIndex = _safe_int(getattr(self, 'levelIndex', 1), 1)
        self.relHt = _safe_float(getattr(self, 'relHt', 0.0), 0.0)
        self.contam = _normalize_contam_overrides(getattr(self, 'contam', None))
        self.element = getattr(self, 'element', None)
        if not self.prjName:
            self.prjName = 'z' + '%03d' % max(int(self.prjIndex), 0)

    @classmethod
    def fromElement(cls, space: MoosasSpace, temperature=27) -> AfnZone:
        """
        Initialize an AfnZone instance with space data and settings.
        
        Parameters
        ----------
        space : MoosasSpace
            The space object containing geometry, settings, and parent project information.
        name : str, optional
            Custom name for the zone. If not provided, defaults to the space ID.
        temperature : float or int, optional
            Operating temperature of the zone in degrees Celsius. Default is 27.
        
        Returns
        -------
        None
            This constructor does not return a value.
        """
        spaceId = space.parent.spaceList.index(space)
        if space.settings['zone_summerrad'] is None:
            try:
                modelRadiation(space.parent, reflection=0)
            except:
                space.settings['zone_summerrad'] = 0
                space.settings['zone_winterrad'] = 0
            space = space.parent.spaceList[spaceId]
        theZone = {}
        theZone["userName"] = space.id
        theZone["temperature"] = temperature
        theZone["prjIndex"] = 0
        theZone["heatLoad"] = 0
        theZone["volume"] = space.area * space.height
        pos = space.floor.getWeightCenter()
        theZone["position_x"] = pos[0]
        theZone["position_y"] = pos[1]
        theZone["position_z"] = pos[2]
        theZone["boundary"] = ' '.join(
            [' '.join(coor) for coor in shapely.get_coordinates(space.edge.force_2d()).astype(str)])
        theZone["prjName"] = ""
        theZone["level"] = _safe_float(getattr(space, "level", pos[2]), pos[2])
        theZone["levelIndex"] = space.parent.levelList.index(space.level) + 1 if space.level in space.parent.levelList else 1
        theZone["relHt"] = pos[2] - theZone["level"]
        theZone["contam"] = {}
        theZone['element'] = space
        z = cls(**theZone)
        z.heatLoad = z.calculateHeatLoad()
        return z

    def calculateHeatLoad(self):
        """
        Calculate the total heat load for a thermal zone.
        
        Parameters
        ----------
        self : object
            The instance of the class containing the settings and area attributes.
            - self.settings (dict): A dictionary containing various zone settings including:
                - 'zone_summerrad' (float): Summer radiation value for the zone.
                - 'zone_ppsm' (float): People per square meter in the zone.
                - 'zone_popheat' (float): Heat gain per person (W/person).
                - 'zone_equipment' (float): Equipment power density (W/m²).
                - 'zone_lighting' (float): Lighting power density (W/m²).
            - self.area (float): Floor area of the zone in square meters.
        
        Returns
        -------
        float
            The total heat load in watts (W), calculated as the sum of solar, occupant,
            equipment, and lighting heat gains.
        """
        def _safe_float(value, default=0.0):
            if value is None:
                return default
            if isinstance(value, str) and value.strip().lower() in ("", "none", "null", "nan"):
                return default
            try:
                return float(value)
            except Exception:
                return default

        def _resolve_setting(value, default=0.0):
            numeric = _safe_float(value, None)
            if numeric is not None:
                return numeric
            if not isinstance(value, str):
                return default
            schedule = getattr(getattr(self.element, "parent", None), "schedule", {}) or {}
            schedule_item = schedule.get(value)
            if not isinstance(schedule_item, dict):
                return default
            schedule_type = str(schedule_item.get("type", "")).strip().lower()
            if schedule_type == "daily":
                daily_values = [_safe_float(v, 0.0) for v in schedule_item.get("value", [])]
                return sum(daily_values) / len(daily_values) if daily_values else default
            if schedule_type == "weekly":
                daily_values = []
                for daily_name in schedule_item.get("value", []):
                    daily_item = schedule.get(str(daily_name))
                    if not isinstance(daily_item, dict):
                        continue
                    if str(daily_item.get("type", "")).strip().lower() != "daily":
                        continue
                    vals = [_safe_float(v, 0.0) for v in daily_item.get("value", [])]
                    if vals:
                        daily_values.append(sum(vals) / len(vals))
                return sum(daily_values) / len(daily_values) if daily_values else default
            return default

        heat = 0
        heat += _resolve_setting(self.element.settings.get('zone_summerrad')) / (
                MoosasCumSky.SUMMER_END_HOY - MoosasCumSky.SUMMER_START_HOY) * 1000 * _resolve_setting(
            self.element.settings.get('zone_win_SHGC'))
        heat += _resolve_setting(self.element.settings.get('zone_ppsm')) * _resolve_setting(
            self.element.settings.get('zone_popheat')) * self.element.area
        heat += _resolve_setting(self.element.settings.get('zone_equipment')) * self.element.area
        heat += _resolve_setting(self.element.settings.get('zone_lighting')) * self.element.area
        return heat

    def printHeatLoad(self):
        """
        Prints the breakdown of heat load components for the zone.
        
        Parameters
        ----------
        self : object
            The instance of the class containing the method. It is expected to have
            attributes `settings`, `area`, and a method `calculateHeatLoad`. The `settings`
            dictionary should contain keys 'zone_summerrad', 'zone_ppsm', 'zone_popheat',
            'zone_equipment', and 'zone_lighting'.
        
        Returns
        -------
        None
            This function does not return any value. It prints the heat load details to stdout.
        """
        def _safe_float(value, default=0.0):
            if value is None:
                return default
            if isinstance(value, str) and value.strip().lower() in ("", "none", "null", "nan"):
                return default
            try:
                return float(value)
            except Exception:
                return default

        def _resolve_setting(value, default=0.0):
            numeric = _safe_float(value, None)
            if numeric is not None:
                return numeric
            if not isinstance(value, str):
                return default
            schedule = getattr(getattr(self.element, "parent", None), "schedule", {}) or {}
            schedule_item = schedule.get(value)
            if not isinstance(schedule_item, dict):
                return default
            schedule_type = str(schedule_item.get("type", "")).strip().lower()
            if schedule_type == "daily":
                vals = [_safe_float(v, 0.0) for v in schedule_item.get("value", [])]
                return sum(vals) / len(vals) if vals else default
            if schedule_type == "weekly":
                vals = []
                for daily_name in schedule_item.get("value", []):
                    daily_item = schedule.get(str(daily_name))
                    if not isinstance(daily_item, dict):
                        continue
                    if str(daily_item.get("type", "")).strip().lower() != "daily":
                        continue
                    daily_vals = [_safe_float(v, 0.0) for v in daily_item.get("value", [])]
                    if daily_vals:
                        vals.append(sum(daily_vals) / len(daily_vals))
                return sum(vals) / len(vals) if vals else default
            return default

        solar = _resolve_setting(self.element.settings.get('zone_summerrad')) / (
            MoosasCumSky.SUMMER_END_HOY - MoosasCumSky.SUMMER_START_HOY
        ) * 1000 * _resolve_setting(self.element.settings.get('zone_win_SHGC'))
        people = _resolve_setting(self.element.settings.get('zone_ppsm')) * _resolve_setting(
            self.element.settings.get('zone_popheat')
        ) * self.element.area
        equipment = _resolve_setting(self.element.settings.get('zone_equipment')) * self.element.area
        lighting = _resolve_setting(self.element.settings.get('zone_lighting')) * self.element.area
        print('\nzone total', solar + people + equipment + lighting)
        print('solar heat', solar)
        print('people', people)
        print('equipment', equipment)
        print('lighting', lighting)
        print('area', self.element.area)

    def toDict(self) -> dict:
        return {
            "userName": self.userName,
            "temperature": self.temperature,
            "prjIndex": self.prjIndex,
            "prjName": self.prjName or ('z' + '%03d' % int(self.prjIndex)),
            "heatLoad": self.heatLoad,
            "volume": self.volume,
            "position_x": self.position_x,
            "position_y": self.position_y,
            "position_z": self.position_z,
            "boundary": self.boundary,
            "level": self.level,
            "levelIndex": self.levelIndex,
            "relHt": self.relHt,
            "contam": dict(self.contam),
        }


class AfnPath(object):
    """
        input for networkFile(paths):
        pathName: user define pathName
        height: height of the aperture in meter (m)
        width: width of the aperture in meter (m)
        positionX,positionY,positionZ: a position to match the path in meter (m)
        fromZone: the zone index that the path from
        toZone: the zone index that the path to
        pressure: wind pressure of the path if it is connected to outdoor
        orientation: orientation of the aperture if it is connected to outdoor
        element: reference MoosasElement (optional)
    """
    __slots__ = ['userName', 'prjIndex', 'pathHeight', 'pathWidth', 'position_x', 'position_y', 'position_z',
                 'fromZone', 'toZone', 'pressure', 'winType', 'orientation', 'pathType',
                 'level', 'levelIndex', 'relHt', 'contam', 'element', 'geometry']

    def __init__(self, **kwargs):
        legacy_geometry = None
        if "element" in kwargs and not isinstance(kwargs.get("element"), dict):
            legacy_geometry = kwargs.get("element")
            kwargs = dict(kwargs)
            kwargs["geometry"] = kwargs.get("geometry", legacy_geometry)
            kwargs.pop("element", None)
        for key in self.__slots__:
            if key in kwargs.keys():
                setattr(self, key, kwargs[key])
        self.prjIndex = _safe_int(getattr(self, 'prjIndex', 0), 0)
        self.pathHeight = None if getattr(self, 'pathHeight', None) is None else _safe_float(getattr(self, 'pathHeight'), 0.0)
        self.pathWidth = None if getattr(self, 'pathWidth', None) is None else _safe_float(getattr(self, 'pathWidth'), 0.0)
        self.position_x = _safe_float(getattr(self, 'position_x', 0.0), 0.0)
        self.position_y = _safe_float(getattr(self, 'position_y', 0.0), 0.0)
        self.position_z = _safe_float(getattr(self, 'position_z', 0.0), 0.0)
        self.fromZone = None if getattr(self, 'fromZone', None) is None else _safe_int(getattr(self, 'fromZone'), -1)
        self.toZone = None if getattr(self, 'toZone', None) is None else _safe_int(getattr(self, 'toZone'), -1)
        self.pressure = _safe_float(getattr(self, 'pressure', 0.0), 0.0)
        self.winType = _safe_int(getattr(self, 'winType', 1), 1)
        self.orientation = _vector_to_data(getattr(self, 'orientation', None))
        inferred_type = getattr(self, "pathType", None)
        if inferred_type is None:
            inferred_dtype = str((getattr(self, "element", None) or {}).get("dtype", "")).strip().lower()
            inferred_type = "leakage" if inferred_dtype == "plr_leak3" else "opening"
        self.pathType = str(inferred_type or "").strip() or "opening"
        self.level = _safe_float(getattr(self, 'level', 0.0), 0.0)
        self.levelIndex = _safe_int(getattr(self, 'levelIndex', 1), 1)
        self.relHt = _safe_float(getattr(self, 'relHt', 0.0), 0.0)
        self.contam = _normalize_contam_overrides(getattr(self, 'contam', None))
        self.geometry = getattr(self, 'geometry', None)
        self.element = _normalize_path_element_data(
            getattr(self, 'element', None),
            path_height=self.pathHeight or 0.0,
            path_width=self.pathWidth or 0.0,
            win_type=self.winType,
            prj_index=self.prjIndex,
            user_name=getattr(self, 'userName', ""),
            operable=kwargs.get("operable"),
            path_type=self.pathType,
        )

    @classmethod
    def fromElement(cls, moGeometry: MoosasGlazing | MoosasSkylight, pathName=None, fromZone=None, toZone=None,
                    pressure=0.0) -> AfnPath:
        """
        Initialize an AfnPath object for airflow network modeling.
        
        Parameters
        ----------
        moGeometry : MoosasGlazing or MoosasSkylight
            The geometry object representing a glazing or skylight, providing face ID, Uid, space, parent face, shading, and orientation.
        model : object
            The model instance to which this path belongs; passed to the parent class constructor.
        pathName : str, optional
            Name identifier for the path. If None, defaults to the Uid of moGeometry.
        fromZone : object, optional
            The zone from which air flows. Default is None.
        toZone : object, optional
            The zone to which air flows. Default is None.
        pressure : float, optional
            Pressure difference across the path, used in airflow calculations. Default is 0.0.
        
        Returns
        -------
        None
            This method initializes the object and does not return a value.
        """
        thePath = {}
        thePath["winType"] = 1 if isinstance(moGeometry, MoosasGlazing) else 0
        thePath["Uid"] = moGeometry.Uid
        if pathName is None:
            pathName = moGeometry.Uid
        thePath["userName"] = pathName
        thePath["prjIndex"] = 0
        thePath["fromZone"] = fromZone
        thePath["toZone"] = toZone
        thePath["pressure"] = pressure
        thePath["orientation"] = moGeometry.orientation if not Vector.parallel(moGeometry.orientation,
                                                                               [0, 0, 1]) else Vector(
            [0, 0,
             1])
        pos = list(moGeometry.getWeightCenter())
        thePath['position_x'] = pos[0]
        thePath['position_y'] = pos[1]
        thePath['position_z'] = pos[2]
        thePath["level"] = _safe_float(getattr(moGeometry, "level", pos[2]), pos[2])
        thePath["levelIndex"] = moGeometry.parent.levelList.index(moGeometry.level) + 1 if moGeometry.level in moGeometry.parent.levelList else 1
        thePath["relHt"] = pos[2] - thePath["level"]
        thePath["pathHeight"] = None
        thePath["pathWidth"] = None
        thePath["contam"] = {}
        thePath["pathType"] = "skylight" if isinstance(moGeometry, MoosasSkylight) else "glazing"
        thePath["element"] = _default_path_element_dict(
            win_type=thePath["winType"],
            prj_index=thePath["prjIndex"],
            user_name=thePath["userName"],
            path_height=0.0,
            path_width=0.0,
            operable=moGeometry.operable,
            path_type=thePath["pathType"],
        )
        thePath["geometry"] = moGeometry
        thePath = cls(**thePath)
        thePath._width
        thePath._height
        thePath.element = _normalize_path_element_data(
            thePath.element,
            path_height=thePath.pathHeight,
            path_width=thePath.pathWidth,
            win_type=thePath.winType,
            prj_index=thePath.prjIndex,
            user_name=thePath.userName,
            path_type=thePath.pathType,
        )
        return thePath

    @property
    def _width(self):
        """
        Calculate the width of the face along the minimum Z-plane.

        Returns
        -------
        float
            The length (magnitude) of the vector representing the width of the face, computed as the 
            distance between the first and last points in the sorted 2D projection of the face's 
            boundary points lying on the minimum Z-plane.
        """
        if self.pathWidth is None:
            coordinates = shapely.get_coordinates(self.geometry.face, include_z=True)
            minZ = np.min(coordinates[:, 2])
            sortlist = [[coor[0], coor[1]] for coor in coordinates if
                        minZ - geom.POINT_PRECISION < coor[2] < minZ + geom.POINT_PRECISION]
            sortlist.sort(key=lambda x: (x[0], x[1]))
            self.pathWidth = Vector(np.array(sortlist[-1]) - np.array(sortlist[0])).length()
        return self.pathWidth

    @property
    def _height(self):
        """
        Height of the path calculated as the ratio of 3D area to width.

        
        Returns
        -------
        float
            The height of the path, computed as the 3D area divided by the width.
        """
        if self.pathHeight is None:
            self.pathHeight = self.geometry.area3d() / self._width
        return self.pathHeight

    def toDict(self) -> dict:
        if self.fromZone is None or self.toZone is None:
            raise Exception('path topology have not been calculated')
        element_data = _normalize_path_element_data(
            self.element,
            path_height=float(self.pathHeight),
            path_width=float(self.pathWidth),
            win_type=self.winType,
            prj_index=self.prjIndex,
            user_name=self.userName,
        )
        element_data.pop("_autoGenerated", None)
        return {
            "userName": self.userName,
            "prjIndex": self.prjIndex,
            "pathHeight": float(self.pathHeight),
            "pathWidth": float(self.pathWidth),
            "position_x": self.position_x,
            "position_y": self.position_y,
            "position_z": self.position_z,
            "fromZone": int(self.fromZone),
            "toZone": int(self.toZone),
            "pressure": self.pressure,
            "winType": self.winType,
            "orientation": _vector_to_data(self.orientation),
            "pathType": self.pathType,
            "level": self.level,
            "levelIndex": self.levelIndex,
            "relHt": self.relHt,
            "contam": dict(self.contam),
            "element": element_data,
        }


class AfnNetwork:
    __slots__ = ('zones', 'paths', 'model', 'levels')

    def __init__(self, model=None, paths=None, zones=None):
        """
        Initialize the object with a model and construct airflow network paths and zones.
        
        Parameters
        ----------
        model : object
            The model containing space and glazing information used to create airflow network 
            paths and zones. Expected to have a `spaceList` attribute with spaces that provide 
            face data via `getAllFaces()`.
        
        Returns
        -------
        None
            This method does not return a value.
        """
        if model:
            self.model = model
            self.levels = _build_level_objects(getattr(model, "levelList", [0.0]))
            self.paths: list[AfnPath] = []
            self.zones: list[AfnZone] = []
            spaces = sorted(
                list(model.spaceList),
                key=lambda s: (
                    _safe_float(getattr(s, "level", 0.0), 0.0),
                    str(getattr(s, "id", getattr(s, "Uid", getattr(s, "userName", "")))),
                ),
            )
            for s in spaces:
                self.zones.append(AfnZone.fromElement(s))
                self.zones[-1].prjIndex = len(self.zones)
                self.zones[-1].prjName = 'z' + '%03d' % int(self.zones[-1].prjIndex)
                zone_paths: list[AfnPath] = []
                for gls in s.getAllFaces(to_dict=False):
                    if isinstance(gls, MoosasGlazing) or isinstance(gls, MoosasSkylight):
                        zone_paths.append(AfnPath.fromElement(gls))
                leak_path = _build_leakage_path_from_space(s, self.zones[-1])
                if leak_path is not None:
                    zone_paths.append(leak_path)
                zone_paths.sort(
                    key=lambda p: (
                        _safe_int(getattr(p, "levelIndex", 1), 1),
                        1 if str(getattr(p, "pathType", "")).strip().lower() == "leakage" else 0,
                        str(getattr(p, "userName", "")),
                    )
                )
                for p in zone_paths:
                    self.paths.append(p)
                    self.paths[-1].prjIndex = len(self.paths)
        elif (paths and zones):
            self.paths = paths
            self.zones = zones
            self.levels = _infer_levels_from_zones(zones)
        self.paths = pathTopology(self.paths, self.zones)
        self.paths, self.zones = cleanseNetwork(self.paths, self.zones)
        if not hasattr(self, "levels"):
            self.levels = _infer_levels_from_zones(self.zones)

    def checkTopology(self):
        topology = {z.prjIndex:[] for z in self.zones}
        topology[-1]=[]
        for p in self.paths:
            topology[p.fromZone].append(p.prjIndex)
            topology[p.toZone].append(p.prjIndex)
        print(topology)
        print({k: len(i) for k, i in topology.items()})

    def applyWindPressure(self, windVector: Vector, speed=None, airDensity=1.205, alpha=0.22):
        """
        Apply wind pressure to the paths of the object.
        
        Parameters
        ----------
        windVector : Vector
            A vector representing the direction and magnitude of the wind.
        speed : float, optional
            The speed of the object relative to the wind. If not provided, defaults to None.
        airDensity : float, default=1.205
            The density of air in kg/m³. Default corresponds to standard conditions at sea level.
        alpha : float, default=0.22
            A coefficient representing the aerodynamic properties of the object.
        
        Returns
        -------
        None
            This method modifies the `paths` attribute in place and does not return a value.
        """
        """connect to applyWindPressure()"""
        self.paths = applyWindPressure(self.paths, windVector=windVector, speed=speed, airDensity=airDensity,
                                       alpha=alpha)

    def applyZoneHeat(self, zoneInfoFile):
        """
        Copy heat information from a zone info file to corresponding zones.
        
        Parameters
        ----------
        zoneInfoFile : str
            Path to the file containing zone information, including heat load and zone names.
            The file is parsed to extract heat data which is then applied to zones.
        
        Returns
        -------
        None
            This function does not return any value. It modifies the `heatLoad` attribute of 
            each zone in `self.zones` if the zone's userName matches an entry in the heat info.
        """
        """copy the heat information in zoneInfoFile"""
        zoneInfo = parseFile(zoneInfoFile)[0]
        heatIdx, nameIdx = 2, 3
        if len(zoneInfo[0]) == 2:
            heatIdx, nameIdx = 1, 2
        heatInfo = {line[nameIdx]: float(line[heatIdx]) for line in zoneInfo}
        for zone in self.zones:
            if zone.userName in heatInfo.keys():
                zone.heatLoad = heatInfo[zone.userName]

    def toFile(self, networkFilePath=None):
        """connect to buildNetworkFile()"""
        return buildNetworkFile(pathList=self.paths, zoneList=self.zones, networkFilePath=networkFilePath)

    def toPrj(self, prjFilePath=None, networkFilePath=None, split=False,
              t0=25, simulate=False, resultFile=None):
        """connect to buildPrj()"""
        return buildPrj(pathList=self.paths, zoneList=self.zones, prjFilePath=prjFilePath,
                        networkFilePath=networkFilePath, split=split,
                        t0=t0, simulate=simulate, resultFile=resultFile)

    def toZoneFile(self, zoneInfoFilePath=None):
        """connect to buildZoneInfoFile()"""
        return buildZoneInfoFile(zoneList=self.zones, pathList=self.paths, zoneInfoFilePath=zoneInfoFilePath)


def applyWindPressure(pathList: list[AfnPath], windVector: Vector, speed: float = None,
                      airDensity=1.205, alpha=0.22) -> list[AfnPath]:
    """
    Apply wind pressure to a list of AfnPath objects based on wind conditions.
    
    Parameters
    ----------
    pathList : list of AfnPath
        List of AfnPath objects to which wind pressure will be applied.
    windVector : Vector
        Direction and magnitude of the wind. If `speed` is provided, the vector is scaled accordingly.
    speed : float, optional
        Wind speed in m/s. If None, the magnitude of `windVector` is used as the wind speed.
    airDensity : float, default=1.205
        Air density in kg/m³, used in pressure calculation.
    alpha : float, default=0.22
        Empirical exponent related to altitude effects on wind pressure.
    
    Returns
    -------
    list of AfnPath
        The input list of AfnPath objects with updated `pressure` attributes.
    """
    """apply wind pressure to paths.

    -------------------------------------------
    pathList: list of AfnPath which need to apply wind pressure
    windVector: a Vector represents the wind direction and speed.
    speed: wind speed unit in m/s, if none, the length of vector will be the wind speed
    airDensity: default is 1.205 kg/m3
    alpha: default 0.22

    -------------------------------------------
    xgboost is large, therefore we import it only if users want a pressure input.
    The output value from call Xgb is the Wind Pressure Coefficient (Wp):

        P = Wp * airDensity * velocity^2 * ((altitude/10)^(alpha * 2)) / 2
        alpha = 0.22
        airDensity = 1.205
    """
    from .ventXgb import pressureInput, callXgb
    if speed is not None:
        windVector *= speed
    xgbInput = [pressureInput(windVector, path) for path in pathList]
    Wp = callXgb(xgbInput)

    pressure = Wp * airDensity * windVector.length(power=True) * np.power(([p.elevation for p in pathList]),
                                                                          (alpha * 2)) / 2
    for _path, _pressure in zip(pathList, pressure):
        if Vector.parallel(_path.normal, [0, 0, 1]):
            _pressure = 0
        _path.pressure = _pressure

    return pathList


def getZoneAndPath(model):
    """
    Constructs zone and path lists from a building model for airflow network analysis.
    
    Parameters
    ----------
    model : object
        A building model object containing a list of spaces (spaceList). The model is used to extract spaces and their glazing elements to construct zones and airflow paths.
    
    Returns
    -------
    zoneList : list of AfnZone
        List of AfnZone objects created from the spaces in the model. Each zone is assigned a unique project index.
    pathList : list of AfnPath
        List of AfnPath objects representing airflow paths through glazing and skylight elements. The list is processed to establish topological relationships between paths and zones.
    """
    pathList: list[AfnPath] = []
    zoneList: list[AfnZone] = []
    spaces = sorted(
        list(model.spaceList),
        key=lambda s: (
            _safe_float(getattr(s, "level", 0.0), 0.0),
            str(getattr(s, "id", getattr(s, "Uid", getattr(s, "userName", "")))),
        ),
    )
    for s in spaces:
        zoneList.append(AfnZone.fromElement(s))
        zoneList[-1].prjIndex = len(zoneList)
        zoneList[-1].prjName = 'z' + '%03d' % int(zoneList[-1].prjIndex)
        zone_paths: list[AfnPath] = []
        for gls in s.getAllFaces(to_dict=False):
            if isinstance(gls, MoosasGlazing) or isinstance(gls, MoosasSkylight):
                zone_paths.append(AfnPath.fromElement(gls))
        leak_path = _build_leakage_path_from_space(s, zoneList[-1])
        if leak_path is not None:
            zone_paths.append(leak_path)
        zone_paths.sort(
            key=lambda p: (
                _safe_int(getattr(p, "levelIndex", 1), 1),
                1 if str(getattr(p, "pathType", "")).strip().lower() == "leakage" else 0,
                str(getattr(p, "userName", "")),
            )
        )
        for p in zone_paths:
            pathList.append(p)
            pathList[-1].prjIndex = len(pathList)
    pathList = pathTopology(pathList, zoneList)
    return zoneList, pathList


def pathTopology(pathList: list[AfnPath], zoneList: list[AfnZone]) -> list[AfnPath]:
    """
    Determine the zone topology for a list of paths based on their connected spaces.
    
    Parameters
    ----------
    pathList : list of AfnPath
        List of AfnPath objects, each representing a path with a `space` attribute 
        containing connected space IDs, and `fromZone` and `toZone` attributes to be set.
    zoneList : list of AfnZone
        List of AfnZone objects, each having an `id` attribute used to map space IDs to zone indices.
    
    Returns
    -------
    list of AfnPath
        Filtered list of AfnPath objects with valid spaces (non-empty), where `fromZone` 
        and `toZone` are set to the corresponding zone indices from `zoneList`. Paths 
        with no connected spaces are excluded.
    """
    zoneUid = {zone.element.id: zone.prjIndex for zone in zoneList}
    invalidPath = []

    for i, p in enumerate(pathList):
        geometry = getattr(p, "geometry", None)
        if geometry is None:
            if p.fromZone is None or p.toZone is None:
                invalidPath.append(i)
            continue
        if len(getattr(geometry, "space", []) or []) == 0:
            invalidPath.append(i)
        elif len(geometry.space) == 1:
            p.fromZone = -1
            if geometry.space[0] in zoneUid.keys():
                p.toZone = zoneUid[geometry.space[0]]
            else:
                invalidPath.append(i)

        elif len(geometry.space) == 2:
            if geometry.space[0] in zoneUid.keys() and geometry.space[1] in zoneUid.keys():
                p.fromZone = zoneUid[geometry.space[0]]
                p.toZone = zoneUid[geometry.space[1]]
            else:
                invalidPath.append(i)

    return list(np.delete(pathList, invalidPath))


def buildNetworkFile(model=None, pathList: list[AfnPath] = None, zoneList: list[AfnZone] = None,
                     networkFilePath=None, windVector: Vector = None,
                     networkDict: dict = None,
                     airDensity=1.205, alpha=0.22) -> str:
    """
        Build *.net file from model or pathList/zoneList.
        It is the input for MoosasAFN.exe and record zone and path data.
        model and pathList/zoneList cannot be all None.
        ------------------------------------------------------

        model : MoosasModel by transforming.transform()
        pathList : you can construct AfnPath by getZoneAndPath() method and edit somthing.
        zoneList : you can construct AfnZone by getZoneAndPath() method and edit somthing.
        file_path : If None, the file string will be returned directly.
        ------------------------------------------------------

        The network file can be decoded like this:
        ! All line with the prefix "!" are annotations and will be ignored.
        ! Zone Data or Path Data are identified be the length of the line, so dont worry about that.
        ! zoneName,zonePrjName,heatLoad,temperature,volume,positionX,positionY,positionZ,boundaryPolygon
        Bedroom0, z01, 1760, 27, 180, 16.2, 18.5, 3.0, 16.2 18.5 20.2 18.5 20.2 23.5 16.2 23.5 (len==9)
        ....
        ! pathName,pathIndex,height,width,positionX,positionY,positionZ,fromZone,toZone,pressure (len==10)
        BedroomWin0, p01, 1.8, 1.2, 17.4, 19.1, 3.6, -1, 2, 12.5
        ....
        ------------------------------------------------------

    """
    if networkDict is not None:
        payload = _normalize_network_payload_data(networkDict, levels_hint=getattr(model, "levelList", None))
        if networkFilePath is None:
            networkFilePath = os.path.join(path.tempDir, generate_code(4) + '.json')
        with open(networkFilePath, 'w+', encoding='utf-8') as f:
            json.dump(payload, f, indent=2)
        return networkFilePath

    if pathList is None or zoneList is None:
        if model is None:
            raise Exception("model, pathList and zoneList cannot be all None")
        zoneList, pathList = getZoneAndPath(model)

    # Always run cleansing here, no matter path/zone source.
    # buildPrj/buildZoneInfoFile may pass pre-built lists and previously bypass cleaning.
    pathList, zoneList = cleanseNetwork(pathList, zoneList)

    if windVector:
        pathList = applyWindPressure(pathList, windVector=windVector, speed=windVector.length(), airDensity=airDensity,
                                     alpha=alpha)
    if networkFilePath is None:
        networkFilePath = os.path.join(path.tempDir, generate_code(4) + '.json')

    level_objects = _build_level_objects(getattr(model, "levelList", None)) if model is not None else _infer_levels_from_zones(zoneList)
    level_map = {round(level["refht"], 6): level["nr"] for level in level_objects}
    for zone in zoneList:
        zone.levelIndex = level_map.get(round(_safe_float(zone.level, 0.0), 6), zone.levelIndex)
        zone.prjName = zone.prjName or ('z' + '%03d' % int(zone.prjIndex))
    for path_item in pathList:
        path_item.levelIndex = level_map.get(round(_safe_float(path_item.level, 0.0), 6), path_item.levelIndex)

    payload = _normalize_network_payload_data({
        "schemaVersion": NETWORK_SCHEMA_VERSION,
        "levels": [{
            "nr": level["nr"],
            "refht": level["refht"],
            "delht": level["delht"],
            "name": _normalize_level_name(level.get("name"), level["nr"]),
        } for level in level_objects],
        "zones": {zone.userName: zone.toDict() for zone in zoneList},
        "paths": {p.userName: p.toDict() for p in pathList},
    }, levels_hint=getattr(model, "levelList", None))

    with open(networkFilePath, 'w+', encoding='utf-8') as f:
        json.dump(payload, f, indent=2)
    return networkFilePath


def ambient_connectivity_report(pathList: list[AfnPath], zoneList: list[AfnZone]) -> dict:
    """
    Audit whether zones are connected to ambient through variable flow paths.

    Returns
    -------
    dict
        Connectivity report with direct/reachable/unreachable zone ids and names.
    """
    zone_ids = [int(z.prjIndex) for z in zoneList]
    zone_id_set = set(zone_ids)
    zone_by_id = {int(z.prjIndex): z for z in zoneList}

    def _is_variable_path(p: AfnPath, eps=1e-9):
        try:
            h = float(p.pathHeight)
            w = float(p.pathWidth)
            return h > eps and w > eps
        except Exception:
            return False

    valid_index_paths: list[AfnPath] = []
    dropped_invalid_index = []
    for i, p in enumerate(pathList):
        fz = int(p.fromZone)
        tz = int(p.toZone)
        f_ok = (fz == -1) or (fz in zone_id_set)
        t_ok = (tz == -1) or (tz in zone_id_set)
        if f_ok and t_ok:
            valid_index_paths.append(p)
        else:
            dropped_invalid_index.append(i)

    topology = {-1: set()}
    for zid in zone_ids:
        topology[zid] = set()

    direct_ambient_zone_ids = set()
    for p in valid_index_paths:
        if not _is_variable_path(p):
            continue
        fz = int(p.fromZone)
        tz = int(p.toZone)
        topology[fz].add(tz)
        topology[tz].add(fz)
        if fz == -1 and tz >= 0:
            direct_ambient_zone_ids.add(tz)
        elif tz == -1 and fz >= 0:
            direct_ambient_zone_ids.add(fz)

    visited = {-1}
    queue = [-1]
    while queue:
        cur = queue.pop(0)
        for nxt in topology.get(cur, ()):
            if nxt not in visited:
                visited.add(nxt)
                queue.append(nxt)

    reachable_zone_ids = sorted([z for z in visited if z >= 0])
    unreachable_zone_ids = sorted(set(zone_ids).difference(reachable_zone_ids))
    return {
        "zone_ids": zone_ids,
        "topology": topology,
        "dropped_invalid_path_indices": dropped_invalid_index,
        "direct_ambient_zone_ids": sorted(direct_ambient_zone_ids),
        "direct_ambient_zone_names": [zone_by_id[zid].userName for zid in sorted(direct_ambient_zone_ids)],
        "reachable_zone_ids": reachable_zone_ids,
        "reachable_zone_names": [zone_by_id[zid].userName for zid in reachable_zone_ids],
        "unreachable_zone_ids": unreachable_zone_ids,
        "unreachable_zone_names": [zone_by_id[zid].userName for zid in unreachable_zone_ids],
        "all_connected_to_ambient": len(unreachable_zone_ids) == 0,
    }


def cleanseNetwork(pathList: list[AfnPath], zoneList: list[AfnZone]) -> (list[AfnPath], list[AfnZone]):
    """
    Clean the zones that are not linked to the ambient and remove associated paths.
    
    Parameters
    ----------
    pathList : list of AfnPath
        List of path objects representing connections between zones. Each path has 'fromZone' and 'toZone' attributes indicating connectivity.
    zoneList : list of AfnZone
        List of zone objects. Each zone object must have an 'id' attribute. Zones not connected to the ambient (index -1) are considered invalid.
    
    Returns
    -------
    tuple of (list of AfnPath, list of AfnZone)
        A tuple containing the filtered pathList and zoneList with unconnected (invalid) zones and their associated paths removed.
        Zone indices in paths are remapped to reflect the new positions after deletion.
    """
    """clean the zones that are not linked to the ambient.
    those zones will cause error in ContamX and their air change is 0.
    """

    zone_count = len(zoneList)
    if zone_count == 0:
        return list(pathList), list(zoneList)

    report = ambient_connectivity_report(pathList=pathList, zoneList=zoneList)
    zone_ids = report["zone_ids"]
    zone_by_id = {int(z.prjIndex): z for z in zoneList}
    keep_zone_ids = report["reachable_zone_ids"]
    remove_zone_ids = report["unreachable_zone_ids"]
    dropped_invalid_index = report["dropped_invalid_path_indices"]
    zone_id_set = set(zone_ids)
    valid_index_paths: list[AfnPath] = []
    for p in pathList:
        fz = int(p.fromZone)
        tz = int(p.toZone)
        f_ok = (fz == -1) or (fz in zone_id_set)
        t_ok = (tz == -1) or (tz in zone_id_set)
        if f_ok and t_ok:
            valid_index_paths.append(p)
    if dropped_invalid_index:
        print(f'******Warning: drop paths with invalid zone index: {dropped_invalid_index}')

    if remove_zone_ids:
        print('******Warning: some zones do not linked to ambient by variable flow path.')
        print(f'******Warning: those zone will be removed:{remove_zone_ids}')

    # Reindex remaining zones to contiguous 1..N and map old zone prjIndex -> new prjIndex.
    idx_map = {old: new for new, old in enumerate(keep_zone_ids, start=1)}
    new_zones: list[AfnZone] = [zone_by_id[i] for i in keep_zone_ids]
    for i, z in enumerate(new_zones, start=1):
        z.prjIndex = i

    new_paths: list[AfnPath] = []
    removed_path_idx = []
    for i, p in enumerate(valid_index_paths):
        fz = int(p.fromZone)
        tz = int(p.toZone)
        f_keep = (fz == -1) or (fz in idx_map)
        t_keep = (tz == -1) or (tz in idx_map)
        if not (f_keep and t_keep):
            removed_path_idx.append(i)
            continue
        p.fromZone = -1 if fz == -1 else idx_map[fz]
        p.toZone = -1 if tz == -1 else idx_map[tz]
        new_paths.append(p)

    if removed_path_idx:
        print(f'******Warning: those path will be removed:{removed_path_idx}')

    for i, p in enumerate(new_paths, start=1):
        p.prjIndex = i

    return new_paths, new_zones


def buildPrj(model=None, pathList: list[AfnPath] = None, zoneList: list[AfnZone] = None,
             prjFilePath=None, networkFilePath=None, split=False,
             t0=25, windVector: Vector = None, airDensity=1.205, alpha=0.22,
             simulate=False, resultFile=None, networkDict: dict = None) -> str:
    """
    Build one or more CONTAM *.prj file(s) from a model or provided path and zone lists.
    
    Parameters
    ----------
    model : MoosasModel, optional
        A model object obtained from transforming.transform(). Used to derive zone and path data if pathList and zoneList are not provided.
    pathList : list of AfnPath, optional
        List of AfnPath objects representing airflow paths. Can be constructed using getZoneAndPath().
    zoneList : list of AfnZone, optional
        List of AfnZone objects representing zones. Can be constructed using getZoneAndPath().
    prjFilePath : str, optional
        File path for the output *.prj file. If None, defaults to a temporary directory under 'data\\vent'.
    networkFilePath : str, optional
        File path for the generated network (.net) input file for MoosasAFN.exe. If None, defaults to a temporary location.
    split : bool, default False
        If True, the network is split into isolated parts and multiple files are generated.
    t0 : float or int, default 25
        Outdoor temperature in degrees Celsius.
    windVector : Vector, optional
        Wind vector defining direction and speed for simulation.
    airDensity : float, default 1.205
        Air density in kg/m³.
    alpha : float, default 0.22
        Power law exponent for airflow modeling.
    simulate : bool, default False
        If True, runs CONTAM simulation after building the project and collects results.
    resultFile : str, optional
        Custom file path to save simulation results. If not specified, defaults to the project directory.
    
    Returns
    -------
    list of str
        A list containing the path(s) to the generated *.prj file(s).
    """
    """
        Build *.prj file(s) from model or pathList/zoneList.
        networkFile,model and pathList/zoneList cannot be all None.
        ------------------------------------------------------

        model : MoosasModel by transforming.transform()
        pathList : you can construct AfnPath by getZoneAndPath() method and edit somthing.
        zoneList : you can construct AfnZone by getZoneAndPath() method and edit somthing.
        prjFilePath : file path to export *.prj file. The directory of this file will be used to export other things.
            If None the file will be exported to data\vent
        networkFilePath : export the MoosasAFN.exe input file here. If None the file will be exported to __temp__
        split : If True, the network will be automatically split into several isolate parts and files.
        t0 : outdoor temperature.
        simulate : If True, contamX will be called and result will be exported to *.prj directory.
        resultFile : you cen redirect the result file to other place.
        ------------------------------------------------------

        Moosas ContamX Builder and reader.
        Command line should be: MoosasAFN.exe [-h,-p...] inputNetworkFile.net
        Optional command:
        -h / -help : reprint the help information
        -p / -project : base name of the prj file  (default: network)
        -d / -directory : directory where the project file and result to put  (default: execution directory)
        -o / -output : result output file path (default: execution directory\airVel.o)
        -r / -run : 1 if run contamX for all built *.prj files and gather the results (default: 0)
        -s / -split : 1 if split the input network into several networks (default: 1)
        -t / -t0 : OutdoorTemperature (default: 25)
    """
    prjTempName = 'afn_' + generate_code(4)
    if networkFilePath is None:
        networkFilePath = os.path.join(path.tempDir, prjTempName + '.json')
        if networkDict is None and (pathList is None or zoneList is None):
            if model is None:
                raise Exception("model, pathList and zoneList cannot be all None")
            zoneList, pathList = getZoneAndPath(model)
        networkFilePath = buildNetworkFile(model=model, pathList=pathList, zoneList=zoneList,
                                           networkFilePath=networkFilePath, windVector=windVector,
                                           networkDict=networkDict, airDensity=airDensity, alpha=alpha)

    if prjFilePath is None:
        prjName = prjTempName
        prjDirectory = path.tempDir
        prjFilePath = os.path.join(prjDirectory, prjName + '.prj')
    else:
        prjName = os.path.basename(prjFilePath)[:-4]
        prjDirectory = os.path.dirname(prjFilePath)

    command = [os.path.join(path.libDir, 'vent', f'MoosasAFN{VENT_EXE_SUFFIX}')]
    command += ['-p', prjName]
    command += ['-d', prjDirectory]
    command += ['-t', str(t0)]
    if resultFile is not None:
        command += ['-o', resultFile]
    if simulate:
        command += ['-r', "1"]
    if not split:
        command += ['-s', "0"]
    command += [networkFilePath]

    callCmd(command)

    return prjFilePath


def buildZoneInfoFile(model=None, zoneList: list[AfnZone] = None, networkFilePath=None, pathList: list[AfnPath] = None,
                      networkDict: dict = None,
                      zoneInfoFilePath=None) -> str:
    """
    Builds a zone information file (.info) for thermal zone data based on model, zone list, and network file inputs.

    Parameters
    ----------
    model : MoosasModel, optional
        The transformed model object obtained from the `transform()` method. Used to extract zone and path data if not provided directly.
    zoneList : list of AfnZone, optional
        List of AfnZone objects representing thermal zones. If not provided, will be extracted from the model.
    networkFilePath : str, optional
        Path to the network file (.net). If not provided, a temporary network file will be generated using `buildNetworkFile()`.
    pathList : list of AfnPath, optional
        List of AfnPath objects representing airflow paths. Required if generating a network file.
    zoneInfoFilePath : str, optional
        Output file path for the generated zone info file. If not specified, a temporary file path is created.

    Returns
    -------
    str
        If `zoneInfoFilePath` is provided, returns generated file path.
        If `zoneInfoFilePath` is None, returns in-memory zoneInfo text stream.
    """
    """
        This method can build the zoneInfo file by:
        model: MoosasModel, given by transforming.transform() method
        zoneList: list[AfnZone], given by getZoneAndPath() method
        networkFile: given by buildNetworkFile() method, or construct by other script like MoosasAFN.exe
        ------------------------------------------------------

        The zoneInfo file can be decoded like this:
        [[prjroomname, roomheatload, userroomname]..[]]
        in which:
            prjroomname: the room name set in the *.prj file, must be the same in every character
            roomheatload: the gross load of the room in (W).
            userroomname: the room name define by the users, and it will occur in the result file.

        The roomInfo file can exclude the roomname and only provide roomInfo, which means that:
        the room heat file can only have 2 columns:
        [[prjroomname,roomheatload]...[]]
        in this case, the roomnome will be the same to the prjroomname

        or 2 columns:
        [[roomheatload,usersroomname]...[]]
        iin this case, the roomInfo data should be in the same sequence of zones in the project file

        or only 1 column:
        [[roomheatload]...[]]
        in this case, the roomheatload data should be in the same sequence of zones in the project file
        ------------------------------------------------------
    """

    zoneStr = []
    zoneStr += ["! All line with the prefix ! are annotations and will be ignored."]
    zoneStr += ["! zonePrjName,heatLoad,zoneName"]
    if networkDict is not None:
        payload = _normalize_network_payload_data(networkDict, levels_hint=getattr(model, "levelList", None))
    else:
        payload = None

    if payload is None and networkFilePath is None:
        prjTempName = 'afn_' + generate_code(4)
        networkFilePath = os.path.join(path.tempDir, prjTempName + '.json')
        if zoneList is None:
            if model is None:
                raise Exception("model, pathList and zoneList cannot be all None")
            zoneList, pathList = getZoneAndPath(model)
        networkFilePath = buildNetworkFile(model=model, pathList=pathList, zoneList=zoneList,
                                           networkFilePath=networkFilePath)
    if payload is None:
        payload = _load_network_payload(networkFilePath)
    zones = sorted(payload.get("zones", {}).values(), key=lambda z: _safe_int(z.get("prjIndex"), 0))
    for zone in zones:
        zoneStr += [','.join([
            str(zone.get("prjName") or ('z' + '%03d' % _safe_int(zone.get("prjIndex"), 0))),
            str(zone.get("heatLoad", 0.0)),
            str(zone.get("userName", "")),
        ])]

    zoneStr = '\n'.join(zoneStr)
    if zoneInfoFilePath is None:
        return zoneStr

    path.checkBuildDir(zoneInfoFilePath)
    with open(zoneInfoFilePath, 'w+') as f:
        f.write(zoneStr)
    return zoneInfoFilePath
